Description: >
  Author - Caleb Ikhuohon
  Capstone project for the Cloud DevOps Nanodegree program

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  KeyPairName:
    Description:  Name of key-pair file (PEM) for SSH login .
    Type: String
    Default: 'capstone-proj'

Resources:

  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref ClusterRole

  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  EKS:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.17"
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${EnvironmentName}-SCG"
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-PUB-NETS

Outputs:
  EksId:
    Description: The EKS id.
    Value: !Ref EKS
    Export:
      Name: !Sub ${EnvironmentName}-EKS

  EKSRoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt ClusterRole.Arn
    Export:
      Name: !Sub "${EnvironmentName}-EKSRoleArn"